<?php echo $header; ?>
<main>
<section class="welcome">
	<div class="container">
		<div class="left">
			<h1>Üdv a Kis Kedvencek kedvenc oldalán!</h1>
			<p>Gazdit keresünk! A régi kitette a lábát, és mi máris itt vagyunk, hogy újat találjunk: Téged! Becs szóra, hűséges társaid leszünk, csak gyűjts össze mindnyájunkat a „A kis kedvencek titkos élete” albumba vagy fém gyűjtődobozba, és ott mi szépen, csendben meglapulunk!</p>
			<p>És hogy lásd, mennyire szeretnénk a kedvedben járni, a kártyagyűjtő akció idejére szuper nyereményjátékkal készülünk és cserebere lehetőséget is biztosítunk. Szóval légyszííí, legyél Te az új gazdink!</p>
			<p class="bold">Kattints, görgess és mindent megtalálsz, amire csak szükséged lehet, hogy jól érezd magad új barátaiddal
			a Kis kedvencek titkos élete hűségakció ideje alatt!</p>
			<a href="#" class="btn yellow">Bővebben</a>
		</div>
		<div class="right"></div>
	</div>
</section>
<section class="extra-cards">
	<div class="container">
		<h1>Szerezz extra kártyákat!</h1>
		<p>Hétről hétre számos termék mellé extra kiskedvences kártya is jár ajándékba. Így hamarabb gyűjtheted össze az albumodba összes kis barátodat! Figyeld akciós újságjainkat további ajánlatokért!</p>
		<a class="video" href="#"></a>
		<div class="products">
			<ul class="clear">
				<li>
					<img src="/<?php echo $this->config->rootDir; ?>/upload/images/index/1.png"
					width="216" height="201"
					srcset="/<?php echo $this->config->rootDir; ?>/upload/images/index/1.png 1x, /<?php echo $this->config->rootDir; ?>/upload/images/index/1-retina.png 2x" alt="Kép1">
					<div class="name">Medve kördobozos <br>sajt</div>
					<div class="description">többféle, 200 g<br>(2.195/1.195 Ft/1 kg helyett 1.645 Ft/1 l)<br>3 darab vásárlása esetén: (1.495 Ft/1 kg)</div>
					<div class="price">439,- helyett<span>329,-</span></div>
					<div class="price-3">3db vásárlása esetén darabja<span>299,-</span></div>
				</li>
				<li>
					<img src="/<?php echo $this->config->rootDir; ?>/upload/images/index/2.png"
					width="187" height="241"
					srcset="/<?php echo $this->config->rootDir; ?>/upload/images/index/2.png 1x, /<?php echo $this->config->rootDir; ?>/upload/images/index/2-retina.png 2x" alt="Kép2">
					<div class="name" style="margin-top: 16px;">Nyírfacukor</div>
					<div class="description">xilit alapú, 500 g<br>(3.798 Ft/1 kg helyett 2.798 Ft/1 kg)<br>A csomagolás áruházanként eltérő lehet!</div>
					<div class="price">1899,- helyett<span>1399,-</span></div>
				</li>
				<li>
					<img src="/<?php echo $this->config->rootDir; ?>/upload/images/index/3.png"
					width="183" height="204"
					srcset="/<?php echo $this->config->rootDir; ?>/upload/images/index/3.png 1x, /<?php echo $this->config->rootDir; ?>/upload/images/index/3-retina.png 2x" alt="Kép3">
					<div class="name">Dr. Oetker muffin <br>csokoládédarabokkal <br>aenean magna ligula <br>dictum elementum</div>
					<div class="description" style="padding-bottom: 43px;">350 g vagy 345 g vagy 456 g<br>(1.540/1.562,32/1.182,02 Ft/1 kg)<br>A választék áruházanként eltérő lehet!</div>
					<div class="price"><span>539,-</span></div>
				</li>
			</ul>
			<a href="#" class="btn yellow">Összes ajánlat</a>
		</div>
	</div>
</section>
</main>
<?php echo $footer; ?>