<?php echo $header; ?>
<main>
<div class="breadcrumb">
	<div class="container">
		<ul>
			<li>
				<a href="#">Főoldal</a>
			</li>
			<li>
				<a href="#" class="active">Impresszum</a>
			</li>
		</ul>
	</div>
</div>
<section class="impress">
	<div class="container">
		<h2>Impresszum</h2>
		<div class="left box-template">
			<p>
				SPAR Magyarország Kereskedelmi Korlátolt Felelősségű Társaság
				Cím: H-2060, Bicske, SPAR út 0326/1.<br>
				Telefonszám: <a href="tel:+36208237000">+36 20 823 70 00</a><br>
				E-mail cím: <a href="mailto:info@spar.hu">info@spar.hu</a><br>
			</p>

			<p>
				Cégbíróság: Székesfehérvári Törvényszék Cégbírósága
				Cégjegyzékszám: 07-09-009192<br>
				Adószám: 10485824-2-07<br>
			</p>
			<p>
				Tárhelyszolgáltató neve: REON Digital Kft.<br>
				Tárhelyszolgáltató címe: H-1113, Budapest, Badacsonyi utca 9.<br>
				Tárhelyszolgáltató e-mail címe: <a href="mailto:info@reondigital.hu">info@reondigital.hu</a><br>
			</p>			
		</div>
		<div class="right"></div>
	</div>
</section>
</main>
<?php echo $footer; ?>