<?php echo $header; ?>
<main>
<div class="breadcrumb">
	<div class="container">
		<ul>
			<li>
				<a href="#">Főoldal</a>
			</li>
			<li>
				<a href="#" class="active">Játék</a>
			</li>
		</ul>
	</div>
</div>
<section class="impress">
	<div class="container">
		<h2>Impresszum</h2>
		<div class="left box-template">
			
		</div>
		<div class="right"></div>
	</div>
</section>
</main>
<?php echo $footer; ?>