<?php echo $header; ?>
<main>
<div class="breadcrumb">
	<div class="container">
		<ul>
			<li>
				<a href="#">Főoldal</a>
			</li>
		</ul>
	</div>
</div>
<section class="notification">
	<div class="container">
		<h2>Értesítés</h2>
		<div class="left box-template">
			<h1>Sikeresen regisztráltál!</h1>
			<p>Már csak az e-mail címedet <span>(xy@email.hu)</span> kell megerősítened, az arra elküldött linkre kattintással. Ha nem találod, nézd meg a SPAM mappádban is.</p>
			<a href="#" class="btn yellow">Tovább</a>
		</div>
		<div class="right positive"></div>
		<div class="right negative"></div>
	</div>
</section>
</main>
<?php echo $footer; ?>