<footer>
	<div class="container">
		<div class="left">
			<a href="#" class="kiskedvencek-logo"></a>
		</div>
		<div class="center">
			<nav>
				<ul>
					<li><a href="#">Impresszum</a></li>
					<li><a href="#">Játékszabályzat</a></li>
					<li><a href="#">Felhasználási feltételek</a></li>
					<li><a href="#">Kapcsolat</a></li>
				</ul>
			</nav>
			<div class="copyright">The Secret Life of Pets © 2016 Universal Studios.</div>
		</div>
		<div class="right">
			<a href="#" class="spar-logo"></a>
		</div>
	</div>
</footer>
</body>
</html>