<footer>
	<div class="container">
		<div class="left">
			<a href="#" class="kiskedvencek-logo"></a>
		</div>
		<div class="center">
			<nav>
				<ul>
					<li><a href="/kiskedvencek/impresszum">Impresszum</a></li>
					<li><a href="#">Játékszabályzat</a></li>
					<li><a href="#">Felhasználási feltételek</a></li>
					<li><a href="#">Kapcsolat</a></li>
				</ul>
			</nav>
			<div class="copyright">The Secret Life of Pets © 2016 Universal Studios.</div>
		</div>
		<div class="right">
			<a href="#" class="spar-logo"></a>
		</div>
	</div>
</footer>
<!-- Gallery -->
<div class="overlay"></div>
<div class="gallery">
	<div class="container">
		<a href="#" class="close"></a>
		<div class="page">
			2/3
		</div>
		<ul>
			<li class="active"></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
		<div class="nav">
			<a href="#" class="left"></a>
			<a href="#" class="right"></a>
		</div>
	</div>
</div>
</body>
</html>