<!DOCTYPE html>
<html lang="hu">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <title></title>
        <meta name="description" content="">
        <!-- Favicons -->
        <!-- Screen CSS -->
        <link href="/<?php echo $this->config->rootDir; ?>/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/css/screen.css" rel="stylesheet">
        <!-- 3rd-party CSS -->
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,800&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Oswald:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:700,400&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <!-- JQuery -->
        <script src="/<?php echo $this->config->rootDir; ?>/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/js/3rd-party/jquery.min.js"></script>
        <!-- 3rd-party JS files -->
        
        <!-- Main JS file -->
        <script src="/<?php echo $this->config->rootDir; ?>/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/js/main.js"></script>
        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
        (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        e.src='https://www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
        ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
    </head>
    <body>
        <!--[if lt IE 9]>
        <p class="browserupgrade"><strong>Elavult</strong> böngészőt használsz. Kérlek <a href="http://browsehappy.com/">tölts le</a> újabb böngészőt, az optimális böngészés érdekében.</p>
        <![endif]-->
        <a name="gallery"></a>
        <header>
            <div class="container">
                <div class="left">
                    <a href="/kiskedvencek/" class="kiskedvencek-logo"></a>
                </div>
                <div class="right">
                    <a href="#" class="spar-logo"></a>
                    <nav>
                        <ul>
                            <li><a class="active" href="/kiskedvencek/promocio">Promóció</a></li>
                            <li><a href="/kiskedvencek/kedvencek">Kedvencek</a></li>
                            <li><a href="#">Cserebere</a></li>
                            <li><a href="/kiskedvencek/jatek">Játék</a></li>
                            <li><a href="/kiskedvencek/roadshow">Roadshow</a></li>
                        </ul>
                    </nav>
                    <a href="#" class="login-button btn yellow">Belépés</a>
                </div>
            </div>
        </header>