<?php echo $header; ?>
<main>
<div class="breadcrumb">
	<div class="container">
		<ul>
			<li>
				<a href="#">Főoldal</a>
			</li>
			<li>
				<a href="#" class="active">Belépés</a>
			</li>
		</ul>
	</div>
</div>
<section class="login">
	<div class="container">
		<h2>Belépés</h2>
		<div class="left box-template">
			<a href="#" class="fb-login">Belépés Facebookkal</a>
			<p>vagy</p>
			<form>
				<div class="form-control">
					<div class="error">Error</div>
					<label for="email">E-mail:</label>
					<input type="email" id="email">					
				</div>
				<div class="form-control password">
					<div class="error">Nagyon durva hiba, eszméletlen</div>
					<label for="password">Jelszó:</label>
					<input type="password" id="password">
					<input type="text" id="password">
					<a href="#" class="show-password"></a>			
				</div>
				<div class="form-control clear">
					<a href="/kiskedvencek/elfelejtett-jelszo" class="forgot-password">Elfelejtettem a jelszavamat!</a>
					<input class="btn yellow" type="submit" value="Belépés">		
				</div>
			</form>
			<div class="not-registered">Még nem regisztráltam. <a href="/kiskedvencek/regisztracio">Regisztráció</a></div>
		</div>
		<div class="right"></div>
	</div>
</section>
</main>
<?php echo $footer; ?>