<?php echo $header; ?>
<main>
<div class="breadcrumb">
	<div class="container">
		<ul>
			<li>
				<a href="#">Főoldal</a>
			</li>
			<li>
				<a href="#" class="active">Regisztráció</a>
			</li>
		</ul>
	</div>
</div>
<section class="register">
	<div class="container">
		<h2>Regisztráció</h2>
		<div class="left box-template">
		<form action="#" method="post" id="avatar">
			<input id="avatar-image" type="file" name="avatar_image">
		</form>
			<div class="top">
				<div class="profile-icon stock-img"></div>
				<label for="avatar-image">Feltöltés</label>
			</div>
			<form>
				<div class="form-control">
					<div class="error">Error</div>
					<label for="last-name">Vezetéknév:</label>
					<input type="text" id="last-name">					
				</div>
				<div class="form-control">
					<div class="error">Error</div>
					<label for="first-name">Keresztnév:</label>
					<input type="text" id="first-name">					
				</div>
				<div class="form-control">
					<div class="error">Error</div>
					<label for="city">Város:</label>
					<input type="text" id="city">					
				</div>
				<div class="form-control">
					<div class="error">Error</div>
					<label for="email">E-mail:</label>
					<input type="text" id="email">					
				</div>
				<div class="form-control password">
					<div class="error">Nagyon durva hiba, eszméletlen</div>
					<label for="password">Jelszó:</label>
					<input type="password" id="password">
					<input type="text" id="password">
					<a href="#" class="show-password"></a>			
				</div>
				<div class="form-control checkbox-1">
					<input type="checkbox" id="checkboxG1" class="css-checkbox" /><label for="checkboxG1" class="css-label">Feliratkozom a SPAR hírlevélre</label>
				</div>
				<div class="form-control checkbox-2">
					<input type="checkbox" id="checkboxG2" class="css-checkbox" /><label for="checkboxG2" class="css-label">Elfogadom a <a href="#">Felhasználási feltételeket</a></label>
				</div>
				<input class="btn yellow" type="submit" value="Regisztráció">
			</form>
			<div class="already-registered">Már regisztráltam. <a href="/kiskedvencek/belepes">Belépés</a></div>
		</div>
		<div class="right"></div>
	</div>
</section>
</main>
<?php echo $footer; ?>