<?php echo $header; ?>
<main>
<div class="breadcrumb">
	<div class="container">
		<ul>
			<li>
				<a href="#">Főoldal</a>
			</li>
			<li>
				<a href="#" class="active">Játék</a>
			</li>
		</ul>
	</div>
</div>
<section class="game">
	<div class="container">
		<h2>Játék</h2>
		<div class="box" style="height: 550px; max-width: 100%; margin: 20px auto 89px; background-color: #000;"></div>
	</div>
</section>
</main>
<?php echo $footer; ?>