<?php echo $header; ?>
<main>
<div class="breadcrumb">
	<div class="container">
		<ul>
			<li>
				<a href="#">Főoldal</a>
			</li>
			<li>
				<a href="#" class="active">Kedvencek</a>
			</li>
		</ul>
	</div>
</div>
<section class="pets">
	<div class="container">
		<h2>Kedvencek</h2>
		<div class="top">
			<div class="left">
				<h1>Nagyvárosi kedvencek</h1>
				<p>A gazdák által dédelgetett és elkényeztetett Nagyvárosi Kedvencek naphosszat egymás lakásait látogatják, lüke sztorikat mesélnek a gazdáikról, nagyszabású kalandokról fantáziálnak, és gyakorolják a cukiságot.</p>
				<p>Minden méretű, formájú és színű állatot szívesen látnak, legyen az apró, mint Norman, a tengerimalac, vagy nagy, mint Leonard, az uszkár, vagy kissé izgága, mint az agyon tutujgatott Max.</p>
			</div>
			<div class="right"></div>
			<div class="clear"></div>
			<ul class="cards">
				<li>
					<a class="max box-template" href="/kiskedvencek/kedvencek/kivalasztott_kedvenc">
						<span>Max</span>
					</a>
				</li>
				<li>
					<a class="duke box-template" href="/kiskedvencek/kedvencek/kivalasztott_kedvenc">
						<span>Duke</span>
					</a>
				</li>
				<li>
					<a class="gigi box-template" href="/kiskedvencek/kedvencek/kivalasztott_kedvenc">
						<span>Gigi</span>
					</a>
				</li>
				<li>
					<a class="mel box-template" href="/kiskedvencek/kedvencek/kivalasztott_kedvenc">
						<span>Mel</span>
					</a>
				</li>
			</ul>
		</div>
		<div class="bottom">
			<div class="left">
				<h1>Kidobott kedvencek</h1>
				<p>A Kidobott Kedvencek a csatorna mélyén élnek, a lehúzott állatok társaságának tagjaiként. Barátokra és népes családra leltek ott, és feltétel nélkül elfogadják vezérüknek Hógolyót.</p>
			</div>
			<div class="right"></div>
			<div class="clear"></div>
			<ul class="cards">
				<li>
					<a class="hogolyo box-template" href="/kiskedvencek/kedvencek/kivalasztott_kedvenc">
						<span>Hógolyó</span>
					</a>
				</li>
				<li>
					<a class="tetko box-template" href="/kiskedvencek/kedvencek/kivalasztott_kedvenc">
						<span>Tetkó</span>
					</a>
				</li>
				<li>
					<a class="harci box-template" href="/kiskedvencek/kedvencek/kivalasztott_kedvenc">
						<span>Harci</span>
					</a>
				</li>
				<li>
					<a class="ozon box-template" href="/kiskedvencek/kedvencek/kivalasztott_kedvenc">
						<span>Ózon</span>
					</a>
				</li>
			</ul>
		</div>
	</div>
</section>
</main>
<?php echo $footer; ?>