<?php echo $header; ?>
<main>
<div class="breadcrumb">
	<div class="container">
		<ul>
			<li>
				<a href="#">Főoldal</a>
			</li>
			<li>
				<a href="#">Kedvencek</a>
			</li>
			<li>
				<a href="#" class="active">Duke</a>
			</li>
		</ul>
	</div>
</div>
<section class="pet">
	<div class="container">
		<h2>Nagyvárosi kedvencek</h2>
		<div class="city clear">
			<div class="left">
				<img src="/<?php echo $this->config->rootDir; ?>/upload/images/pet/1.png"
				width="700" height="525"
				srcset="/<?php echo $this->config->rootDir; ?>/upload/images/pet/1.png 1x, /<?php echo $this->config->rootDir; ?>/upload/images/pet/1-retina.png 2x" alt="Kép1">
			</div>
			<div class="right">
				<h3>Duke</h3>
				<p>Duke kemény leckéket kapott az élettől. Valaha volt gazdája, akitől szeretetet kapott. De egyszer, amikor kiszaladt a házból, eltévedt, és a sintértelepen kötött ki.
					Onnan mentette ki a lágyszívű Katie.
				Most csak arra vágyik, hogy az új gazdája szeresse – és hogy elfoglalja Max terepét.</p>
			</div>
		</div>
		<div class="clear"></div>
		<div class="channel clear">
			<div class="right">
				<img src="/<?php echo $this->config->rootDir; ?>/upload/images/pet/2.png"
				width="469" height="348"
				srcset="/<?php echo $this->config->rootDir; ?>/upload/images/pet/2.png 1x, /<?php echo $this->config->rootDir; ?>/upload/images/pet/2-retina.png 2x" alt="Kép2">
			</div>
			<div class="left">
				<h3>Ózon</h3>
				<p>Ózon egy vagány macska a sikátorból, aki erőteljesen utálja a kutyákat, és az undok kóbormacskákból álló bandájával tartja őket rettegésben.</p>				
			</div>
		</div>
		<!--
		<h4>Képek</h4>
		<div class="pictures">
			<ul>
				<li>
					<a href="#gallery">
						<img src="/<?php echo $this->config->rootDir; ?>/upload/images/gallery/1.png"
						width="469" height="348px"
						srcset="/<?php echo $this->config->rootDir; ?>/upload/images/gallery/1.png 1x, /<?php echo $this->config->rootDir; ?>/upload/images/gallery/1-retina.png 2x">
					</a>
				</li>
				<li>
					<a href="#gallery">
						<img src="/<?php echo $this->config->rootDir; ?>/upload/images/gallery/1.png"
						width="469" height="348px"
						srcset="/<?php echo $this->config->rootDir; ?>/upload/images/gallery/1.png 1x, /<?php echo $this->config->rootDir; ?>/upload/images/gallery/1-retina.png 2x">
					</a>
				</li>
				<li>
					<a href="#gallery">
						<img src="/<?php echo $this->config->rootDir; ?>/upload/images/gallery/1.png"
						width="469" height="348px"
						srcset="/<?php echo $this->config->rootDir; ?>/upload/images/gallery/1.png 1x, /<?php echo $this->config->rootDir; ?>/upload/images/gallery/1-retina.png 2x">
					</a>
				</li>
			</ul>
		</div>
		<h4>Videó</h4>
		<div class="videos">
			<ul>
				<li>
					<a href="#">
						<img src="/<?php echo $this->config->rootDir; ?>/upload/images/gallery/1.png"
						width="469" height="348px"
						srcset="/<?php echo $this->config->rootDir; ?>/upload/images/gallery/1.png 1x, /<?php echo $this->config->rootDir; ?>/upload/images/gallery/1-retina.png 2x">
					</a>
				</li>
				<li>
					<a href="#">
						<img src="/<?php echo $this->config->rootDir; ?>/upload/images/gallery/1.png"
						width="469" height="348px"
						srcset="/<?php echo $this->config->rootDir; ?>/upload/images/gallery/1.png 1x, /<?php echo $this->config->rootDir; ?>/upload/images/gallery/1-retina.png 2x">
					</a>
				</li>
				<li>
					<a href="#">
						<img src="/<?php echo $this->config->rootDir; ?>/upload/images/gallery/1.png"
						width="469" height="348px"
						srcset="/<?php echo $this->config->rootDir; ?>/upload/images/gallery/1.png 1x, /<?php echo $this->config->rootDir; ?>/upload/images/gallery/1-retina.png 2x">
					</a>
				</li>
			</ul>
		</div>
		-->
	</div>
</section>
</main>
<?php echo $footer; ?>