<?php echo $header; ?>
<main>
<div class="breadcrumb">
	<div class="container">
		<ul>
			<li>
				<a href="#">Főoldal</a>
			</li>
			<li>
				<a class="active" href="#">Cserebere</a>
			</li>
		</ul>
	</div>
</div>
<section class="partners swap">
	<div class="container">
		<h2>Cserebere</h2>
		<ul class="navigation">
			<li><a href="/kiskedvencek/cserebere/varazskartyak">Varázskártyák</a></li>
			<li><a class="active" href="/kiskedvencek/cserebere/partnerek">Partnerek</a></li>
			<li><a href="/kiskedvencek/cserebere/listam/keresem">Listám</a></li>
			<li><a href="/kiskedvencek/cserebere/uzenetek">Üzenetek</a></li>
		</ul>
		<div class="bix-box clear no-partner">
			<div class="left box-template">
				<h1>Nincsenek üzeneteid.</h1>
				<p>Partnerekre csak úgy találsz, ha neked is van kínálatod vagy keresett varázskártyád.<br>
				Kattints a "Varázskártyák" oldalra, itt tudsz kártyákat hozzáadni a<br>listáidhoz.</p>
				<a href="#" class="btn yellow">Varázskártyák</a>
			</div>
			<div class="right"></div>
		</div>
		<div class="bix-box">
		</div>
	</div>
</section>
</main>
<?php echo $footer; ?>