<?php echo $header; ?>
<main>
<div class="breadcrumb">
	<div class="container">
		<ul>
			<li>
				<a href="#">Főoldal</a>
			</li>
			<li>
				<a class="active" href="#">Cserebere</a>
			</li>
		</ul>
	</div>
</div>
<section class="message swap">
	<div class="container">
		<h2>Cserebere</h2>
		<ul class="navigation">
			<li><a href="/kiskedvencek/cserebere/varazskartyak">Varázskártyák</a></li>
			<li><a href="/kiskedvencek/cserebere/partnerek">Partnerek</a></li>
			<li><a href="/kiskedvencek/cserebere/listam/keresem">Listám</a></li>
			<li><a class="active" href="/kiskedvencek/cserebere/uzenetek">Üzenetek</a></li>
		</ul>
		<div class="bix-box box-template">
			<div class="top">
				<div class="profile-i-and-n">
					<div class="icon"></div>
					<div class="name-and-city">
						<div class="name">Nagyerdőssy Bendegúz Vájszíti</div>
						<div class="city">Budapest</div>
					</div>
				</div>
				<div class="searched-and-offered">
					<div class="searched">
						<span>8</span> általad keresett matrica
						<ul>
							<li>3.</li>
							<li>7.</li>
							<li>23.</li>
							<li>21.</li>
							<li>10.</li>
							<li>9.</li>
							<li>32.</li>
						</ul>
					</div>
					<div class="offered">
						<span>8</span> általad keresett matrica
						<ul>
							<li>3.</li>
							<li>7.</li>
							<li>23.</li>
							<li>21.</li>
							<li>10.</li>
							<li>9.</li>
							<li>32.</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="message-box box-template">
				<div class="name-and-date">
					<div class="name">Jon Snow</div>
					<div class="date">2016.05.09. 09:28</div>
				</div>
				<div class="text-message">
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur perferendis expedita, fugit esse voluptates repudiandae ipsa eaque ex aliquid harum error temporibus facilis magni deleniti incidunt quis iusto minus provident.
					<br><br>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit omnis totam aspernatur ex sequi officia facere aliquam, laborum soluta temporibus. Nobis doloremque soluta impedit nisi dignissimos dolor, vero recusandae temporibus.
				</div>
			</div>
			<div class="message-box box-template">
				<div class="name-and-date">
					<div class="name">Jon Snow</div>
					<div class="date">2016.05.09. 09:28</div>
				</div>
				<div class="text-message">
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur perferendis expedita, fugit esse voluptates repudiandae ipsa eaque ex aliquid harum error temporibus facilis magni deleniti incidunt quis iusto minus provident.
					<br><br>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit omnis totam aspernatur ex sequi officia facere aliquam, laborum soluta temporibus. Nobis doloremque soluta impedit nisi dignissimos dolor, vero recusandae temporibus.
				</div>
			</div>
			<form>
						<a href="#" class="delete-all">Beszélgetés törlése</a>
				<h5>Üzenek neki</h5>
				<input type="text">
				<textarea></textarea>
				<input type="submit" value="Küldés" class="btn yellow">
			</form>
		</div>
	</div>
</section>
</main>
<?php echo $footer; ?>