<?php echo $header; ?>
<main>
<div class="breadcrumb">
	<div class="container">
		<ul>
			<li>
				<a href="#">Főoldal</a>
			</li>
			<li>
				<a class="active" href="#">Cserebere</a>
			</li>
		</ul>
	</div>
</div>
<section class="partner swap">
	<div class="container">
		<h2>Cserebere</h2>
		<ul class="navigation">
			<li><a href="/kiskedvencek/cserebere/varazskartyak">Varázskártyák</a></li>
			<li><a class="active" href="/kiskedvencek/cserebere/partnerek">Partnerek</a></li>
			<li><a href="/kiskedvencek/cserebere/listam/keresem">Listám</a></li>
			<li><a href="/kiskedvencek/cserebere/uzenetek">Üzenetek</a></li>
		</ul>
		<div class="left box-template">
			<div class="profile-i-and-n clear">
				<div class="icon"></div>
				<div class="name-and-city">
					<div class="name">Nagyerdőssy Bendegúz Vájszíti</div>
					<div class="city">Budapest</div>
				</div>
			</div>
			<div class="searched-and-offered clear">
				<div class="searched">
					<span>8</span> általad keresett matrica
					<ul>
						<li>3.</li>
						<li>7.</li>
						<li>23.</li>
						<li>21.</li>
						<li>10.</li>
						<li>9.</li>
						<li>32.</li>
					</ul>
				</div>
				<div class="offered">
					<span>8</span> általad keresett matrica
					<ul>
						<li>3.</li>
						<li>7.</li>
						<li>23.</li>
						<li>21.</li>
						<li>10.</li>
						<li>9.</li>
						<li>32.</li>
					</ul>
				</div>
			</div>
			<form>
				<h5>Üzenek neki</h5>
				<input type="text">
				<textarea></textarea>
				<input type="submit" value="Küldés" class="btn yellow">
			</form>
		</div>
		<div class="right">
			<div class="partner-list box-template">
				<div class="profile-i-and-n clear">
					<div class="icon"></div>
					<div class="name-and-city">
						<div class="name">Nagyerdőssy Bendegúz Vájszíti</div>
						<div class="city">Budapest</div>
					</div>
				</div>
				<div class="searched">
					<span>31</span> általad keresett matrica
				</div>
				<div class="offered">
					<span>32</span> általad kínált matrica
				</div>
			</div>
			<div class="partner-list box-template">
				<div class="profile-i-and-n clear">
					<div class="icon"></div>
					<div class="name-and-city">
						<div class="name">Nagyerdőssy Bendegúz Vájszíti</div>
						<div class="city">Budapest</div>
					</div>
				</div>
				<div class="searched">
					<span>31</span> általad keresett matrica
				</div>
				<div class="offered">
					<span>32</span> általad kínált matrica
				</div>
			</div>
			<div class="partner-list box-template">
				<div class="profile-i-and-n clear">
					<div class="icon"></div>
					<div class="name-and-city">
						<div class="name">Nagyerdőssy Bendegúz Vájszíti</div>
						<div class="city">Budapest</div>
					</div>
				</div>
				<div class="searched">
					<span>31</span> általad keresett matrica
				</div>
				<div class="offered">
					<span>32</span> általad kínált matrica
				</div>
			</div>
			<a href="#" class="btn grey">Összes partner</a>
		</div>
	</div>
</section>
</main>
<?php echo $footer; ?>