<?php echo $header; ?>
<main>
<div class="breadcrumb">
	<div class="container">
		<ul>
			<li>
				<a href="#">Főoldal</a>
			</li>
			<li>
				<a href="#" class="active">Promóció</a>
			</li>
		</ul>
	</div>
</div>
<section class="promo">
	<div class="container">
		<div class="left">
			<h1>A hűségakciókról</h1>
			<p>A jutalmazást nem csak a kis kedvencek imádják, hanem a gazdik is.<br>
			Ezért ha most a SPAR, INTERSPAR, City SPAR, SPAR partner és SPAR market áruházakban vásárolunk, minden elköltött 4000 Ft után jutalmul
			1 db ingyenes varázskártyát kapunk a pénztárnál.</p>
			<p>A varázskártya-kollekció legjobb helye a gyűjtőalbum, amit 899 Ft-ért szerezhetünk be az áruházakban, de ugyanilyen menő, ha a 429 Ft-os fém gyűjtődobozban tartjuk kedvenceinket.</p>
			<p>Persze, aki türelmetlen, és minél előbb szeretné, hogy összejöjjön mind a 36 féle varázskártyája, annak két lehetőség is kínálkozik:</p>
			<ul>
				<li>megvásárolhat egy kártyát tartalmazó csomagot a pénztárnál 99 Ft/db áron,</li>
				<li>olyan, hétről hétre változó akciós termékeket vásárol, amik mellé extrakártya is jár ajándékba.</li>
			</ul>
			<p class="footer">A kis kedvencek titkos élete akció 2016. július 28. és 2016. szeptember 21. között tart, illetve a készlet erejéig.</p>
		</div>
		<div class="right"></div>
	</div>
</section>
</main>
<?php echo $footer; ?>