<?php echo $header; ?>
<main>
<div class="breadcrumb">
	<div class="container">
		<ul>
			<li>
				<a href="#">Főoldal</a>
			</li>
			<li>
				<a href="#" class="active">Roadshow</a>
			</li>
		</ul>
	</div>
</div>
<section class="roadshow">
	<div class="container">
		<h2>Roadshow</h2>
		<div class="box-template">
			<div class="top">
				<p class="red">Mi imádunk játszani és te?</p>
				<p>Kattints, és itt nyomon követheted, épp melyik áruházban játszhatsz a szuper nyereményekért! Gyere, várunk!</p>
				<div class="form-control">
					<label for="address">Cím:</label>
					<select id="address">
						<option selected disabled>Mind</option>
						<option>Annyira</option>
						<option>Nem</option>
					</select>
				</div>
				<div class="form-control">
					<label for="date">Dátum:</label>
					<select id="date">
						<option selected disabled>Mind</option>
						<option>Annyira</option>
						<option>Nem</option>
					</select>
				</div>
			</div>
			<div class="table-box">
				<table>
					<tr>
						<td>Dátum <span></span><span></span></td>
						<td>Időpont <span></span><span></span></td>
						<td>Cím <span></span><span></span></td>
						<td>SPAR üzlet <span></span><span></span></td>
					</tr>
					<?php for ($i=0; $i < 50; $i++) {
					?>
					<tr>
						<td>2016-05-10</td>
						<td>9:00</td>
						<td>1083 Budapest, Szigony utva 12.</td>
						<td>SPAR Szupermarket</td>
					</tr>
					<?php
					} ?>
				</table>
			</div>
			<div class="table-box-mobile">
				<div class="sort">
					<div class="row">
						<a href="">Üzlet:</a>
						<a href="">Dátum:</a>
					</div>
					<div class="row">
						<a href="">Időpont:</a>
						<a href="">Cím:</a>
					</div>
				</div>
				<div class="list">
					<div class="row two clear">
						<div class="date">
							<span>Dátum:</span>
							2016-05-10
						</div>
						<div class="time">
							<span>Időpont:</span>
							10:00
						</div>
					</div>					
					<div class="row">
						<div class="address">
							<span>Cím:</span>
							1083 Budapest, Szigony utca 12.
						</div>
						<div class="name">
							<span>Üzlet:</span>
							SPAR Szupermarket
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
</main>
<?php echo $footer; ?>